baseURL = "https://uapi-group.org"
languageCode = "en-us"
title = "The Linux Userspace API Group"
theme = "hugo-book"

[[menu.after]]
  name = "General Documentation"
  url = "https://uapi-group.org/docs"
  weight = 10
[[menu.after]]
  name = "Specifications"
  url = "https://uapi-group.org/specifications"
  weight = 11
[[menu.after]]
  name = "Kernel Feature Ideas"
  url = "https://uapi-group.org/kernel-features"
  weight = 12

[[menu.after]]
  name = "⸻"
  weight = 20
[[menu.after]]
  name = "Collaborate on Github"
  url = "https://github.com/uapi-group"
  weight = 21

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
  BookSearch = false
